import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.scss'
import React from 'react'
import Link from 'next/link'
import { Header } from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Notification Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <div>
          <div>
            <img src='.\assets\images\avatar-mark-webber.webp'></img>
            <div>
              <label htmlFor="">Mark Webber</label>
              <label htmlFor="">reacted to your recent post</label>
              <label htmlFor="">My first tournament today!</label>
            </div>
            <div>
              <label htmlFor="">1m ago</label>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
